name: self-hosted-workflow
on:
  pull_request:
    branches: [ "main" ]

jobs:
  gpu-h100:
    runs-on: cern-nextgen-h100 
    container: registry.cern.ch/ngt-wp1.7/wp1.7-soa-wrapper:latest
    steps:
      - uses: actions/checkout@v4

      - name: Install boost
        run: |
          dnf install -y boost-devel

      - name: cvmfs
        run: |
          ls /cvmfs/atlas.cern.ch/repo
      - name: nvidia-smi
        run: |
          nvidia-smi

      - name: Compile and run CUDA tests
        working-directory: ${{ github.workspace }}/tests
        run: |
          cmake -B build
          cmake --build build --parallel
          ctest --test-dir build --output-on-failure
