name: self-hosted-workflow
on:
  workflow_dispatch:

jobs:
  gpu-h100:
    runs-on: cern-nextgen-h100 
    container: registry.cern.ch/ngt/lxplus-like:9 
    steps:
      - name: cvmfs
        run: |
          ls /cvmfs/atlas.cern.ch/repo
      - name: nvidia-smi
        run: |
          nvidia-smi
